export const SET_RANDOM_COCKTAILS = 'SET_RANDOM_COCKTAILS';
export const GET_RANDOM_COCKTAILS = 'GET_RANDOM_COCKTAILS';
export const SET_SEARCH_COCKTAILS = 'SET_SEARCH_COCKTAILS';
export const GET_SEARCH_COCKTAILS = 'GET_SEARCH_COCKTAILS';
