export const SET_RANDOM_COCKTAILS = 'SET_RANDOM_COCKTAILS';
export const GET_RANDOM_COCKTAILS = 'GET_RANDOM_COCKTAILS';
export const SET_SEARCH_COCKTAILS = 'SET_SEARCH_COCKTAILS';
export const GET_SEARCH_COCKTAILS = 'GET_SEARCH_COCKTAILS';
export const SET_LETTER_COCKTAILS = 'SET_LETTER_COCKTAILS';
export const GET_LETTER_COCKTAILS = 'GET_LETTER_COCKTAILS';
export const SET_ALL_COCKTAILS = 'SET_ALL_COCKTAILS';
export const GET_ALL_COCKTAILS = 'GET_ALL_COCKTAILS';
export const SET_ALL_INGREDIENT = 'SET_ALL_INGREDIENT';
export const GET_ALL_INGREDIENT = 'GET_ALL_INGREDIENT';
export const SET_MODAL_INGREDIENT = 'SET_MODAL_INGREDIENT';
export const GET_MODAL_INGREDIENT = 'GET_MODAL_INGREDIENT';

